apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowPrivilegeEscalation
metadata:
  name: pod-can-escalate-privilege
  namespace: "gatekeeper-system"
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: ["kube-*", "gatekeeper-*"]
