---
apiVersion: v1
data:
  squid.conf: |
    acl localnet src 0.0.0.0/0.0.0.0
    acl SSL_ports port 443
    acl Safe_ports port 80 21 443 70 210 1025-65535 280 488 591 777
    acl CONNECT method CONNECT
    http_access allow all
    http_port 3128
    coredump_dir /var/spool/squid
    cache_dir ufs /var/spool/squid 100 16 256
    maximum_object_size 4096 KB
kind: ConfigMap
metadata:
  name: squid-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: squid
  name: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - image: ubuntu/squid:latest
        name: squid
        volumeMounts:
        - mountPath: /etc/squid/
          name: squid-volume
      volumes:
      - name: squid-volume
        configMap:
          name: squid-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: squid
  name: squid
spec:
  ports:
  - port: 3128
    protocol: TCP
    targetPort: 3128
  selector:
    app: squid
  type: NodePort
