linux:
  hosts:
    node1:
      ansible_host: 192.168.0.1
      ansible_ssh_private_key_file: ~/.ssh/private_key
    node2:
      ansible_host: 192.168.0.2
      ansible_ssh_private_key_file: ~/.ssh/private_key
