---
  - name: system setup
    hosts: linux
    become: yes
    tasks:
    - name: system is updated
      apt:
        name: "*"
        state: latest
        update_cache: yes
    - name: dependencies are installed
      apt:
        name:
          - ca-certificates
          - curl
          - git
        state: latest
    - name: apparmor is installed
      apt:
        name: apparmor
        state: latest
    - name: openjdk-25-jre is installed
      apt:
        name: openjdk-25-jre
        state: latest
    - name: add docker repo
      copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable
    - name: download docker key
      uri:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0755'
    - name: docker is installed
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

